### ISSUE TITLE
FRED API to require HTTPS August 18.

### ISSUE THREAD

**Issue by kgtaylor** [nomadbyte/fredcpp#1]
Hello,
I work on FRED at the St. Louis Fed.  Beginning on August 18, 2015, the FRED API will require HTTPS requests.  This change will help provide secure communication with the FRED API.  An automatic redirect will forward HTTP requests to HTTPS.  We recommend that you update the URLs in your code.  The API currently supports HTTPS to allow you to test your applications with this secure protocol.
Please contact us at webmaster@research.stlouisfed.org or 314-444-FRED (3733) if you have questions or concerns.  Thanks for using FRED and the FRED API.

Sincerely,
Keith Taylor
keith.g.taylor@stls.frb.org

**Comment by nomadbyte** [comment]
Thank you for letting us know about the FRED API changes.
We updated `fredcpp` to generate HTTPS requests to FRED API, which is included in the latest `fredcpp-0.7.0` release: https://github.com/nomadbyte/fredcpp/releases/tag/version-0.7.0
Also, `fredcpp` documentation was updated to describe configuration changes needed in the user's environment to properly handle HTTPS certificate verification for FRED API.
